### ISSUE TITLE
Compatibility issues with CocoaLumberjack 2.0 and dynamic frameworks

### ISSUE THREAD

**Issue by chrisballinger** [swisspol/GCDWebServer#214] opened 2015-09-11 21:55 UTC
I've noticed an issue when trying to compile with this configuration.

**Comment by chrisballinger** [comment] 2015-09-11 21:58
Ah I see the issue. It's that the podspec for GCDWebServer doesn't specify a dependency on CocoaAsyncSocket so the linker step fails

**Comment by swisspol** [comment] 2015-09-11 22:00
GCDWebServer doesn't use CocoaAsyncSocket or any other third-party library actually.

If CocoaLumberjack is in your project, it will just attempt to use for logging instead of its internal system, but it doesn't need it at all. This doesn't seem like a GCDWebServer issue.

**Comment by chrisballinger** [comment] 2015-09-11 22:06
Oh yeah exactly, but the dynamic detection of CocoaLumbjerjack headers within GCDWebServer means that it pulls in the dependency but doesn't link against it. I can't remove CLJ from my project because it is a hard dependency for YapDatabase, and I can't figure out how to force Cocoapods to link GCDWebServer with CLJ without forking your podspec and including it as an explicit dependency.

**Comment by swisspol** [comment] 2015-09-11 22:09
Maybe you can add CocoaLumbjerjack as a direct dependency of your project? In any case, I'm not sure I understand why this is not working: CocoaLumbjerjack is by definition needed by another part of your app, so it should be linked independently of GCDWebServer. Maybe the CocoaPods dependency resolver has a bug.

**Comment by chrisballinger** [comment] 2015-09-11 22:30
When using static linking it works as intended, but when using dynamic frameworks it won't link GCDWebServer with CLJ because it isn't listed as a dependency in the podspec.

My app and other framework targets link with CLJ without any issue, the problem is that each dynamic framework needs to be explicitly linked against its dependencies. The Cocoapods dependency resolver won't try to link CLJ with GCDWebServer because it isn't mentioned anywhere in the GCDWebServer podspec.

The ways to solve this are either:

1) Add CLJ as a subspec dependency in the GCDWebServer podspec. A subspec would probably be ideal so others who encounter this issue can resolve it easily, and it would avoid bundling CLJ for people who don't desire it.
2) Remove the dynamic detection of CLJ headers in GCDWebServer when using dynamic linking
3) Continue to use static linking... which is not ideal once you start including Swift in your projects.

Hope this helps clear it up :)

**Comment by swisspol** [comment] 2015-09-11 22:40
Or:
4) Don't use CocoaPods.

I still don't understand how this is even a problem. GCDWebServer source code is supposed to be embedded as-is into the host target, not to be built as a framework by CocoaPod (even though since then framework targets have been added, but that was for Carthage). This has worked fine with or without CLJ for more than a year. CocoaPods ads all the source files to the project, and then everything gets built and linked into a single target, so what you describe cannot happen.

**Comment by swisspol** [comment] 2015-09-11 22:41
Or:
5) Use `__GCDWEBSERVER_LOGGING_HEADER__` to force-define a custom logging header so that CLJ doesn't get picked up (see header for docs)

**Comment by chrisballinger** [comment] 2015-09-13 00:01
Hey sorry, I didn't mean to offend or sound confrontational. I'll try out 5 since it seems to be the only workable solution without modifying the podspec.

I can 100% guarantee that this problem exists as described and that your description of how CocoaPods works only applies to how it works when using static linking, e.g. when you aren't opting-in to `use_frameworks!` in your Podfile. This is how CocoaPods used to work since the beginning, but that all changed after they added dynamic framework support.

The reason it has worked for more than a year is that the dynamic framework support in CocoaPods is new and the problem only appears when integrating as a dynamic framework. Dynamic frameworks are crucial for interoperability with Swift code, and this only started to affect me after trying to switch.

**Comment by swisspol** [comment] 2015-09-13 00:05
Oh no, I didn't read it that way, no need to apologize :) I was just saying I was still not understanding what was the root cause, but your latest explanation covers it now!

Except it still unclear which frameworks are being created by CocoaPods? One per pod? What's the advantage of the frameworks in the first place?

Do you have a link about these "dynamic frameworks": I'm never heard that specific term. By definition Obj-C frameworks are linked dynamically.

**Comment by chrisballinger** [comment] 2015-09-13 01:25
Here's two helpful links that I've used in the past:

1. http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/
2. http://blog.cocoapods.org/CocoaPods-0.36/

So when using `use_frameworks!` CocoaPods creates a new framework for each Pod (e.g. CocoaLumberjack.framework and GCDWebServer.framework) and then also a monolithic framework that links against all the others, Pods.framework. When building each framework, it will link it with other frameworks specified as dependencies in the podspec. If any single framework imports headers but can't find the corresponding symbols during its own linking step, it will fail.

The advantages: Prior to iOS 8 you had to use static linking for "security reasons", but Apple added signed dynamic framework support to help bridge the gap with Swift / modules. Without dynamic frameworks, you can't easily use 3rd party Swift libraries in your Obj-C code and vice versa.

**Comment by swisspol** [comment] 2015-09-21 15:54
> So when using use_frameworks! CocoaPods creates a new framework for each Pod and then also a monolithic framework that links against all the others, Pods.framework.

That seems pretty typical of CocoaPods of always choosing the most complex solution. Why not a single framework upfront? What advantage could there be in the app to link against 10 frameworks? On the contrary, among other things, it prevents efficient dead code removal.

In any case, does CocoaPods defines an #ifdef constant when it builds? Then it would be simple to disable the CLJ behavior in that very specific case.

**Comment by chrisballinger** [comment] 2015-09-21 18:44
I think `COCOAPODS=1` might be available?

I was wrong about the monolithic `Pods.framework`, it's only a virtual target and it just triggers the build process for each individual framework, not actually linked with your app.

I think the main benefit to having the frameworks split up individually is that it makes it a lot easier to use with Swift modules (e.g. `import GCDWebServer`), and to share framework code between app extensions / other targets.

**Comment by swisspol** [comment] 2015-10-04 19:37
So which solution did you end up choosing? Do you want to send a PR?

**Comment by ericreid** [comment] 2015-10-09 16:43
@chrisballinger I'm having the same issue and would be curious to know if/how you solved this.

**Comment by ericreid** [comment] 2015-10-09 17:08
And just for others who might be stuck by this, here is my ugly hack that you can stick at the end of your Podfile:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name.include?("GCDWebServer")
                puts "Adding fake '__GCDWEBSERVER_LOGGING_HEADER__' macro info to #{target.name} #{config.name}"
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '__GCDWEBSERVER_LOGGING_HEADER__=\"GCDWebServer.h\"', 'GWS_LOG_DEBUG(...)', 'GWS_LOG_VERBOSE(...)', 'GWS_LOG_INFO(...)', 'GWS_LOG_WARNING(...)', 'GWS_LOG_ERROR(...)', 'GWS_LOG_EXCEPTION(__EXCEPTION__)']
            end
        end
    end
end
```

**Comment by adib** [comment] 2015-10-24 02:47
@ericreid Wouldn't those empty `GWS_LOG_xxx` macros effectively disable logging in `GCDWebServer`?

**Comment by cipherCOM** [comment] 2015-10-27 10:06
I would rather propose linking in the CocoaLumberjack framework instead of completely gutting out logging. To actually do this use the following snippet within your Podfile

```
post_install do |installer|
    # Link logging framework for GCDWebServer
    installer.pods_project.targets.each do |target|
        next unless target.product_name.include?("GCDWebServer")
        target.build_configurations.each do |config|
            config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)', '-iquote "$CONFIGURATION_BUILD_DIR/CocoaLumberjack.framework/Headers"']
            config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)', '-framework "CocoaLumberjack"']
        end
    end
end
```

@swisspol This is actually caused by a combination of CococaPods and the way GCDWebServer tries to use CocoaLumberjack. Dynamic frameworks needs all symbols resolved instead of how static libraries work and using the log defines of CocoaLumberjack causes DDLog to be used implicitly within GCDWebServer. I would not propose a PR for the actual code / Podspec but rather embed the above snipped within the README as a necessary step for others.

**Comment by swisspol** [comment] 2015-10-27 15:08
@cipherCOM Is there no way to move this logic into the GCDWebServer Podfile?

**Comment by cipherCOM** [comment] 2015-10-27 15:12
I think one could leverage subspecs to add the dependency. Think of it that way:
– pod "GCDWebServer": By default only the main podspec is used (as of now)
– pod "GCDWebServer/CocoaLumberjack": Now the default + the dependency on CocoaLumberjack is added.
Maybe this will work but I can't say for sure.

**Comment by swisspol** [comment] 2015-10-27 15:14
That makes sense and I don't see why it wouldn't work.

**Comment by swisspol** [comment] 2016-01-15 18:18
This is covered by #256.

**Closed by swisspol** 2016-01-15 18:18 UTC
Labels: bug
